- name: Add pool-id
  become_user: root
  shell: subscription-manager attach --pool=4028bc1574def021017564c05ee803b9
  when: attach_pool|bool == true
  ignore_errors: yes

- name: Enable a PostgreSQL 13 repository
  rhsm_repository:
    name: JSC_OTP_BANK_Postgres_OSS_postgres13_for_rhel7
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == '7'

- name: Enable a pg_probackup repository
  rhsm_repository:
    name: JSC_OTP_BANK_Postgres_OSS_pg_probackup_for_rhel7
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == '7'
        
- name: Install packages system
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ os_pkg }}"
  tags: install_postgres