- name: Install packages pgsql
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ pg_13 }}"
  tags: install_postgres
- name: Change service postgresql-13
  become_user: root
  template:
    src: templates/postgresql-13.service.j2
    dest: /usr/lib/systemd/system/postgresql-13.service
    owner: root
    group: root
    mode: 0644