- name: install HAproxy
  become_user: root
  yum:
    name:
      - haproxy
    state: present
  tags: haproxy

- name: selinux
  become_user: root
  shell: setsebool -P haproxy_connect_any=1
  tags: haproxy
#- name: selinux | set haproxy_connect_any flag to enable tcp connections
#  seboolean:
#    name: haproxy_connect_any
#    state: true
#    persistent: true  

- name: Copy haproxy.cfg
  become_user: root
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  tags: haproxy

- name: Enable Haproxy.service
  systemd:
    name: haproxy
    enabled: yes
  tags: haproxy

- name: Start service Haproxy
  systemd:
    name: haproxy
    state: restarted
  tags: haproxy  