- name: install keepalived
  become_user: root
  yum:
    name:
      - keepalived
    state: present
  tags: keepalived
  
- name: Copy keepalived.conf
  become_user: root
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644

- name: Make sure the "/usr/libexec/keepalived" directory exists
  file:
    dest: /usr/libexec/keepalived
    state: directory
    owner: root
    group: root
  tags: keepalived_conf, keepalived

- name: Create vrrp_script "/usr/libexec/keepalived/haproxy_check.sh" 
  copy:
    content: |
      #!/bin/bash
      /bin/kill -0 `cat /run/haproxy.pid`
    dest: /usr/libexec/keepalived/haproxy_check.sh
    owner: root
    group: root
    mode: 0700

- name: Enable keepalived.service
  systemd:
    name: keepalived
    enabled: yes

- name: Start service keepalived
  systemd:
    name: keepalived
    state: restarted   
  tags: keepalived