- block:
    - name: Check postgresql cluster health
      run_once: true
      become: true
      become_user: postgres
      command: patronictl -c /opt/patroni/patroni.yml list
      register: patronictl_result
      environment:
        PATH: "{{ ansible_env.PATH }}:/home/postgres/.local/bin/:/usr/bin:/usr/local/bin"
      changed_when: false

    - name: PostgreSQL Cluster health
      run_once: true
      debug:
        var: patronictl_result.stdout_lines
  ignore_errors: true
  tags: patroni_status