- name: Upgrade pip
  become_user: root
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3
  tags: pip_update

- name: Install Patroni
  become_user: postgres
  pip:
    name:
      - patroni[raft]
      - psycopg2-binary
    extra_args: --user
    executable: pip3
  tags: install_ptaroni_raft
    
- name: Create config patroni
  become_user: root
  template:
    src: templates/patroni.yml.j2
    dest: /opt/patroni/patroni.yml
    owner: postgres
    group: postgres
    mode: 0644
  tags: install_ptaroni_raft

- name: Copy patroni-raft.service
  become_user: root
  copy:
    src: files/patroni-raft.service
    dest: /usr/lib/systemd/system/patroni-raft.service
    owner: postgres
    group: postgres
    mode: 0644
  tags: install_ptaroni_raft

- name: Enable patroni-raft.service
  systemd:
    name: patroni-raft
    enabled: yes
  tags: install_ptaroni_raft
 
- name: restart patroni-raft
  become_user: root
  systemd:
    state: restarted
    name: patroni-raft
  tags: install_ptaroni_raft