- name: Chown /var/run/postgresql
  become_user: root
  shell: chown postgres:postgres /var/run/postgresql
  args:
    executable: /bin/bash
  tags: pre_install

- name: Upgrade pip
  become_user: root
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3
  tags: pip_update

- name: Install Patroni
  become_user: postgres
  pip:
    name:
      - patroni[raft]
      - psycopg2-binary
    extra_args: --user
    executable: pip3
  tags: install_ptaroni

- name: Create config patroni
  become_user: postgres
  template:
    src: templates/patroni.yml.j2
    dest: /opt/patroni/patroni.yml
    owner: postgres
    group: postgres
    mode: 0644
  tags: install_ptaroni

- name: Copy patroni.service
  become_user: root
  copy:
    src: files/patroni.service
    dest: /usr/lib/systemd/system/patroni.service
    owner: postgres
    group: postgres
    mode: 0644
  tags: install_ptaroni

- name: Enable patroni.service
  systemd:
    name: patroni
    enabled: yes
  tags: install_ptaroni
 
- name: Restart Patroni
  become_user: root
  systemd:
    state: restarted
    name: patroni
  tags: install_ptaroni