- name: Prepare PostgreSQL | Who Master!?
  become: true
  become_user: postgres
  command: "{{ pg_bin }}/psql -p {{ pg_port }} -Aqtc 'SELECT pg_is_in_recovery();'"
  register: pg_is_in_recovery

- block: 
    - name: Add extensions to the databases
      become: true
      become_user: postgres
      postgresql_ext:
        db: "{{ item.db }}"
        name: "{{ item.ext }}"
        login_unix_socket: "{{ pg_unix_socket_dir }}"  # added in 2.8
        port: "{{ pg_port }}"
        state: present
      ignore_errors: true
      loop: "{{ pg_extensions | flatten(1) }}"
      when:
      - pg_is_in_recovery.stdout == "f"
      - pg_extensions is defined
      - pg_extensions | length > 0
      tags: pg_extensions