- name: Install OS+PostgreSQL pkg for Master/Replica
  hosts: postgres_cluster
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - vars/main.yml
    - vars/install_roles.yml

  roles:  
  - role: pre_install
  - role: pkg

- name: Install and Deploy raft node
  hosts: raft
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - vars/main.yml
    - vars/install_roles.yml

  roles:
  - role: pre_install
  - role: install_raft

- name: Deploy PostgreSQL
  hosts: postgres_cluster
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - vars/main.yml
    - vars/install_roles.yml

  roles:
  - role: install_patroni
  - role: check_patroni
  - role: install_haproxy_keepalived
  - role: crontab
  - role: deploy_finish
#  - role: pg_probackup