- hosts: postgres_cluster
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - vars/main.yml

  roles:  
    - role: pg_extensions